### ISSUE TITLE
how to setup bios items?

### ISSUE THREAD

**Issue by LiveSalton** [FilippoGiombi/EFI-Opencore-i7-6700k-Asrock-Z170-OC-Formula#1]
I'm very interested in knowing how to set up the BIOS, and I've been toying with it for days with little success. If convenient, can the MAC OS download address be provided?

**Comment by FilippoGiombi** [comment]
Watch it: https://dortania.github.io/OpenCore-Install-Guide/config.plist/skylake.html#intel-bios-settings

you can download macOS from Mac AppStore

**Comment by LiveSalton** [comment]
>  can i use this version for your efi?
https://blog.daliansky.net/macOS-BigSur-11.6.6-20G624-Release-version-with-OC-0.8.0-and-Clover-5142-and-PE-original-image.html

**Comment by FilippoGiombi** [comment]
Yes

**Comment by LiveSalton** [comment]
thank you very much !!
